Vagrant.configure(2) do |config|

  # Ansible Server
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
    ansible.vm.hostname = "ansible"
    ansible.vm.provision "shell", path: "install_ansible.sh"
    ansible.vm.network "private_network", ip: "192.168.10.1"
    ansible.vm.provider "virtualbox" do |v|
      v.name = "ansible"
      v.memory = 1024
      v.cpus = 1
    end
  end

 # Target Server
  config.vm.define "target" do |target|
    target.vm.box = "ubuntu/bionic64"
    target.vm.hostname = "target"
    target.vm.network "private_network", ip: "192.168.10.2"
    target.vm.provision "shell", path: "configure_servers_target.sh"
    target.vm.provider "virtualbox" do |v|
      v.name = "target"
      v.memory = 1024
      v.cpus = 1
    end
  end

end